name: CI

on:
  push:
    branches: [main]

env:
  binary: sweeps
  CARGO_TERM_COLOR: always

jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: install trunk
        run: cargo install trunk
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Fetch external dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

#      - name: Run clippy
#        uses: actions-rs/clippy-check@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          args: -- -D warnings

#      - name: Run cargo fmt
#        uses: actions-rs/cargo@v1
#        with:
#          command: fmt
#          args: --all -- --check

      - name: Trunk build
        run: trunk build --release
      - name: Prepare package
        run: cp -r assets dist/
      - name: Coerce absolute paths to relative
        run: sed "s@'/@'./@g" ./dist/index.html | sed 's@"/@"./@g' > ./dist/_index.html  && mv ./dist/_index.html ./dist/index.html
      - name: Package as a zip
        uses: vimtor/action-zip@v1
        with:
          files: dist
          dest: ${{ env.binary }}.zip

      - name: Upload binaries as release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-wasm-${{ github.run_number }}.zip
          tag: ${{ github.ref }}-${{ github.run_number }}-rel
          overwrite: true

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: Sweeps
          ITCH_USER: Earthmark
          PACKAGE: ${{ env.binary }}.zip
